import React from 'react';
import {
  // Navigation et interface
  HomeIcon,
  ChatBubbleLeftRightIcon,
  CalendarDaysIcon,
  ChartBarSquareIcon,
  Cog6ToothIcon,
  
  // Authentification et utilisateurs
  UserCircleIcon,
  UserGroupIcon,
  LockClosedIcon,
  EyeIcon,
  EyeSlashIcon,
  
  // Médical
  HeartIcon,
  ClipboardDocumentListIcon,
  DocumentTextIcon,
  PlusIcon,
  PhoneIcon,
  VideoCameraIcon,
  
  // Actions
  PencilSquareIcon,
  TrashIcon,
  ArrowDownTrayIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  MicrophoneIcon,
  
  // États et notifications
  CheckCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  XCircleIcon,
  ClockIcon,
  
  // Interface
  Bars3Icon,
  XMarkIcon,
  MagnifyingGlassIcon,
  AdjustmentsHorizontalIcon,
  
} from '@heroicons/react/24/outline';

import {
  // Versions solides pour les états actifs
  HomeIcon as HomeSolidIcon,
  ChatBubbleLeftRightIcon as ChatSolidIcon,
  CalendarDaysIcon as CalendarSolidIcon,
  ChartBarSquareIcon as ChartSolidIcon,
  HeartIcon as HeartSolidIcon,
  CheckCircleIcon as CheckSolidIcon,
} from '@heroicons/react/24/solid';

import {
  // Icônes Lucide pour le médical spécialisé
  Stethoscope,
  Pill,
  Activity,
  Users,
  FileText,
  Calendar,
  MessageCircle,
  Shield,
  AlertCircle,
  Settings,
  User,
  Search,
  Filter,
  MoreHorizontal,
  Phone,
  Video,
  Send,
  Paperclip,
  Mic,
  Download,
  Edit,
  Trash2,
  X,
  Check,
  Clock,
  ChevronRight,
  ChevronDown,
  Plus,
  Menu,
  LogOut,
  Bell,
  Mail,
  MapPin,
  Star,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  ArrowLeft,
  ArrowRight,
  Refresh,
  
  // Ajouts pour les icônes médicales
  Thermometer,
  Syringe,
  Heart,
  Brain,
  Smile,
  AlertTriangle,
  Monitor,
  Cpu,
  Bot,
  Save,
  Upload,
  Image,
  FileImage,
  Folder,
  FolderOpen,
  Archive,
  Bookmark,
  BookmarkPlus,
  Tag,
  Tags,
  Link,
  ExternalLink,
  Copy,
  Share,
  Flag,
  Target,
  Zap,
  Wifi,
  WifiOff,
  Battery,
  Signal,
  Volume2,
  VolumeX,
  Play,
  Pause,
  Square,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Maximize,
  Minimize,
  RotateCcw,
  RotateCw,
  ZoomIn,
  ZoomOut,
  Move,
  Crop,
  Scissors,
  PaintBucket,
  Palette,
  Brush,
  Pen,
  PenTool,
  Type,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  List,
  ListOrdered,
  Quote,
  Code,
  Columns,
  Grid,
  Layers,
  Layout,
  Sidebar,
  PanelLeft,
  PanelRight,
  PanelTop,
  PanelBottom,
  Database,
  HardDrive,
  Server,
  Cloud,
  CloudUpload,
  CloudDownload,
  Wifi as WifiIcon,
  Globe,
  Monitor,
  Smartphone,
  Tablet,
  Laptop,
  Camera,
  Webcam,
  MousePointer,
  Keyboard,
  Headphones,
  Speaker,
  Microphone,
  Radio,
  Bluetooth,
  Usb,
  HardDriveIcon,
  MemoryStick,
  SdCard,
  Sim,
  CreditCard,
  Banknote,
  Coins,
  DollarSign,
  Euro,
  PoundSterling,
  Yen,
  Calculator,
  PieChart,
  BarChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  Activity as ActivityIcon,
  Pulse,
  Thermometer,
  Droplets,
  Wind,
  Sun,
  Moon,
  Cloud as CloudIcon,
  CloudRain,
  CloudSnow,
  Zap as ZapIcon,
  Umbrella,
  Sunrise,
  Sunset,
  Navigation,
  Compass,
  Map,
  MapPin as MapPinIcon,
  Route,
  Car,
  Truck,
  Bus,
  Train,
  Plane,
  Ship,
  Bike,
  Footprints,
  Fuel,
  Construction,
  Hammer,
  Wrench,
  Screwdriver,
  Paintbrush,
  Ruler,
  Triangle,
  Square as SquareIcon,
  Circle,
  Pentagon,
  Hexagon,
  Octagon,
  Star as StarIcon,
  Heart as HeartLucideIcon,
  Smile,
  Frown,
  Meh,
  Angry,
  Laugh,
  Surprised,
  Confused,
  Sleepy,
  Wink,
  Kiss,
  Tongue,
  Crying,
  Worried,
  Expressionless,
  Neutral,
  Relieved,
  Disappointed,
  Persevering,
  Triumph,
  Joy,
  Sob,
  Tired,
  Sleeping,
  Dizzy,
  Astonished,
  Hushed,
  Flushed,
  Grinning,
  Kissing,
  SmilingEyes,
  Laughing,
  Yum,
  Stuck,
  MoneyMouth,
  Nerd,
  Sunglasses,
  Clown,
  Cowboy,
  Partying,
  Disguised,
  Robot,
  Cat,
  Dog,
  Mouse,
  Hamster,
  Rabbit,
  Fox,
  Bear,
  Panda,
  Koala,
  Tiger,
  Lion,
  Cow,
  Pig,
  Frog,
  Monkey,
  Chicken,
  Penguin,
  Bird,
  Baby,
  Boy,
  Girl,
  Man,
  Woman,
  OlderMan,
  OlderWoman,
  Person,
  People,
  Family,
  Couple,
  TwoMen,
  TwoWomen,
  Couple2,
  Kiss2,
  CoupleHeart,
  Family2,
  Woman2,
  Man2,
  Girl2,
  Boy2,
  Baby2,
  OlderWoman2,
  OlderMan2,
  ManBeard,
  WomanBlond,
  ManBlond,
  WomanCurly,
  ManCurly,
  WomanBald,
  ManBald,
  WomanWhite,
  ManWhite,
  WomanRed,
  ManRed,
  PersonBald,
  PersonCurly,
  PersonWhite,
  PersonRed,
  PersonBlond,
} from 'lucide-react';

// Icônes pour la navigation principale
export const NavigationIcons = {
  Dashboard: ChartBarSquareIcon,
  DashboardSolid: ChartSolidIcon,
  Chat: MessageCircle,
  ChatSolid: ChatSolidIcon,
  Consultation: Stethoscope,
  ConsultationSolid: HeartSolidIcon,
  Admin: Settings,
  Home: HomeIcon,
  HomeSolid: HomeSolidIcon,
};

// Icônes pour l'authentification
export const AuthIcons = {
  User: User,
  UserGroup: Users,
  Lock: Lock,
  Unlock: Unlock,
  Eye: Eye,
  EyeOff: EyeOff,
  Login: LogOut,
  Logout: LogOut,
  Shield: Shield,
};

// Icônes médicales spécialisées
export const MedicalIcons = {
  // Soins et examens
  Stethoscope: Stethoscope,
  Thermometer: Thermometer,
  Pill: Pill,
  Syringe: Syringe,
  
  // Personnel et consultation
  Doctor: User,
  Nurse: Users,
  Patient: User,
  
  // Spécialités
  Heart: Heart,
  Brain: Brain,
  Eye: Eye,
  Tooth: Smile,
  
  // Documents et rendez-vous
  Document: FileText,
  Files: Archive,
  Appointment: Calendar,
  Prescription: FileText,
  
  // Urgences et surveillance
  Emergency: AlertTriangle,
  Monitor: Monitor,
  Activity: Activity,
  
  // Intelligence artificielle et assistance
  AI: Cpu,
  Robot: Bot,
  Assistant: User
};

// Icônes pour les actions
export const ActionIcons = {
  Add: Plus,
  Plus: Plus,
  Edit: Edit,
  Delete: Trash2,
  Save: Save,
  Cancel: X,
  Confirm: Check,
  Search: Search,
  Filter: Filter,
  Download: Download,
  Upload: Upload,
  Share: Share,
  Copy: Copy,
  Send: Send,
  Call: Phone,
  Phone: Phone,
  Video: Video,
  Message: MessageCircle,
  Attach: Paperclip,
  Mic: Mic,
  More: MoreHorizontal,
  Settings: Settings,
  Refresh: Refresh,
  Back: ArrowLeft,
  Forward: ArrowRight,
  Up: ChevronDown,
  Down: ChevronDown,
  Right: ChevronRight,
  Menu: Menu,
  Close: X,
};

// Icônes pour les états et statuts
export const StatusIcons = {
  Success: Check,
  Error: X,
  Warning: AlertCircle,
  Info: InformationCircleIcon,
  Pending: Clock,
  Active: CheckSolidIcon,
  Inactive: XCircleIcon,
  Online: Wifi,
  Offline: WifiOff,
  Loading: Refresh,
  Notification: Bell,
  Star: StarIcon,
  Bookmark: Bookmark,
  Flag: Flag,
  Target: Target,
  Zap: ZapIcon,
};

// Icônes pour les fichiers et dossiers
export const FileIcons = {
  File: FileText,
  FolderIcon: Folder,
  FolderOpen: FolderOpen,
  Image: Image,
  Archive: Archive,
  Link: Link,
  ExternalLink: ExternalLink,
  Tag: Tag,
  Tags: Tags,
};

// Icônes pour les communications
export const CommunicationIcons = {
  Phone: Phone,
  Video: Video,
  Message: MessageCircle,
  Mail: Mail,
  Chat: MessageCircle,
  Send: Send,
  Receive: ArrowLeft,
  Attach: Paperclip,
  Mic: Microphone,
  Speaker: Speaker,
  Mute: VolumeX,
  Unmute: Volume2,
};

// Wrapper pour les icônes avec props communes
export const Icon = ({ 
  icon: IconComponent, 
  size = 'w-5 h-5', 
  className = '', 
  color = 'text-current',
  ...props 
}) => {
  return (
    <IconComponent 
      className={`${size} ${color} ${className}`} 
      {...props} 
    />
  );
};

// Composant d'icône médical avec couleurs spécialisées
export const MedicalIcon = ({ 
  icon: IconComponent, 
  size = 'w-6 h-6', 
  variant = 'primary',
  className = '',
  ...props 
}) => {
  const variantClasses = {
    primary: 'text-blue-600',
    success: 'text-green-600',
    warning: 'text-yellow-600', 
    danger: 'text-red-600',
    secondary: 'text-gray-600',
    medical: 'text-blue-700',
    emergency: 'text-red-700',
    heart: 'text-red-500',
    pulse: 'text-green-500',
  };

  return (
    <IconComponent 
      className={`${size} ${variantClasses[variant] || variantClasses.primary} ${className}`} 
      {...props} 
    />
  );
};

export default {
  NavigationIcons,
  AuthIcons,
  MedicalIcons,
  ActionIcons,
  StatusIcons,
  FileIcons,
  CommunicationIcons,
  Icon,
  MedicalIcon,
};
